name: Main workflow

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  COVERAGE: '1'
  default_php_version: '8.0'
  php_extensions: 'pcov, json'

jobs:
  lint:
    name: 'Lint code'
    uses: './.github/workflows/lint.yml'
    env:
      php_version: 8.0
      extensions: intl, pcov
    with:
      php-version: ${{ env.php_version }}
      php-extensions: ${{ env.extensions }}

  analyze:
    name: 'Analyze code'
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.0', '8.1', '8.2' ]
    uses: './.github/workflows/analyze.yml'
    with:
      php-version: ${{ matrix.php-versions }}
      php-extensions: '$PHP_EXTENSIONS'

  composer-require-check:
    name: 'Composer Require check'
    uses: './.github/workflows/composer-require-check.yml'
    with:
      php-version: '$DEFAULT_PHP_VERSION'
      php-extensions: '$PHP_EXTENSIONS'

  composer-unused-check:
    name: 'Composer Require check'
    uses: './.github/workflows/composer-unused-check.yml'
    with:
      php-version: '$DEFAULT_PHP_VERSION'
      php-extensions: '$PHP_EXTENSIONS'

  composer-audit:
    name: 'Composer Audit'
    uses: './.github/workflows/composer-audit.yml'
    with:
      php-version: '$DEFAULT_PHP_VERSION'
      php-extensions: '$PHP_EXTENSIONS'
