name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

env:
  COVERAGE: '1'
  php-extensions: 'pcov json'

jobs:
  lint:
    name: 'Lint PHP'
    uses: './.github/workflows/lint.yml'
    with:
      php-version: '8.0'
      php-extensions: '${{ env.php-extensions }}'
